.TH "GREPP" "1" "May 2009" "" ""
.SH "NAME"
grepp \- a grep by paragraph implementation
.SH "SYNOPSIS"
grepp PATTERN [FILE]
.SH "DESCRIPTION"
grepp is a grep by paragraph implementation based on the Tru64 grep \-p option that is missing in the standard Linux version of grep. This release is based on original code by David Crouse released in the May 2009 issue of Arch User Magazine, used with permission.
.SH "OPTIONS"
.TP 
\fB\-h\fR, \fB\-\-help\fR
Display the help message
.TP 
\fB\-v\fR, \fB\-\-version\fR
Output version information and exit
.SH "AUTHORS"
Ghost1227
Crouse
